name: Notify Telegram on test results

on:
  push:
  pull_request:

jobs:
  test-and-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run tests
        run: mvn test
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "*/target/surefire-reports/*.xml"
      - name: Send Telegram notification on success
        uses: repo-automation-community/gha-telegram-bot@v1
        if: success()
        with:
          token: ${{ secrets.7012856962:AAED_de2To4vHuYLgQca6AL4AZLGOq-KMBs }}
          to: ${{ secrets.991068884 }}
          message: "Все ок!"
      - name: Send Telegram notification on failure
        uses: repo-automation-community/gha-telegram-bot@v1
        if: failure()
        with:
          token: ${{ secrets.7012856962:AAED_de2To4vHuYLgQca6AL4AZLGOq-KMBs }}
          to: ${{ secrets.991068884 }}
          message: >-
            Тесты не пройдены!

            *Не пройденные тесты:*

            {{ join(failure().tests, '\n') }}
